### 数组的创建和访问

In [1]:
import numpy as np

In [2]:
list_1 = [1, 2, 3, 4]
list_1

[1, 2, 3, 4]

In [4]:
array_1 = np.array(list_1)
array_1

array([1, 2, 3, 4])

In [5]:
list_2 = [5, 6, 7, 8]
array_2 = np.array([list_1, list_2])
array_2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [6]:
array_2.shape

(2, 4)

In [7]:
array_2.size

8

In [8]:
array_2.dtype

dtype('int32')

In [9]:
array_3 = np.array([[1.0, 1, 2],[4.0, 5, 6]])
array_3.dtype

dtype('float64')

In [11]:
array_4 = np.arange(1, 10, 2)
array_4

array([1, 3, 5, 7, 9])

In [12]:
np.zeros(5)

array([ 0.,  0.,  0.,  0.,  0.])

In [13]:
np.zeros((2, 3))

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [14]:
np.eye(5)

array([[ 1.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  1.]])

In [15]:
np.eye(5).dtype

dtype('float64')

In [17]:
a = np.arange(1, 10)
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
a[1]

2

In [19]:
a[1:5]

array([2, 3, 4, 5])

In [20]:
b = np.array([[1, 2, 3], [4, 5, 6]])
b

array([[1, 2, 3],
       [4, 5, 6]])

In [21]:
b[1][0]

4

In [22]:
b[1,0]

4

In [23]:
c = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
c

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [25]:
c[:2, 1:]

array([[2, 3],
       [5, 6]])