### 快速创建数组

In [1]:
import numpy as np

In [2]:
np.random.randn(10)

array([ 1.04742339,  0.50178129, -0.74611731,  0.84159187,  1.92428232,
        0.40752297,  0.32817972,  0.85389028,  0.52847794, -0.67934394])

In [5]:
np.random.randint(10, size=(2, 3))

array([[7, 3, 7],
       [8, 3, 3]])

In [6]:
np.random.randint(10, size=20)

array([4, 9, 7, 6, 5, 8, 7, 0, 9, 4, 2, 3, 6, 4, 9, 1, 2, 7, 9, 3])

In [7]:
np.random.randint(10, size=20).reshape(4, 5)

array([[7, 6, 3, 5, 5],
       [0, 8, 8, 2, 6],
       [0, 3, 4, 8, 8],
       [1, 0, 1, 6, 4]])

### 数组的运算

In [8]:
a = np.random.randint(10, size=20).reshape(4, 5)
b = np.random.randint(10, size=20).reshape(4, 5)

In [9]:
a

array([[8, 9, 2, 4, 7],
       [9, 2, 5, 0, 8],
       [5, 3, 3, 0, 0],
       [8, 3, 1, 5, 1]])

In [10]:
b

array([[0, 7, 2, 5, 3],
       [1, 9, 3, 9, 6],
       [5, 4, 2, 4, 9],
       [2, 2, 5, 9, 1]])

In [11]:
a + b

array([[ 8, 16,  4,  9, 10],
       [10, 11,  8,  9, 14],
       [10,  7,  5,  4,  9],
       [10,  5,  6, 14,  2]])

In [12]:
a - b

array([[ 8,  2,  0, -1,  4],
       [ 8, -7,  2, -9,  2],
       [ 0, -1,  1, -4, -9],
       [ 6,  1, -4, -4,  0]])

In [13]:
a * b

array([[ 0, 63,  4, 20, 21],
       [ 9, 18, 15,  0, 48],
       [25, 12,  6,  0,  0],
       [16,  6,  5, 45,  1]])

In [14]:
a / b

D:\Anaconda3\lib\site-packages\ipykernel\__main__.py:1: RuntimeWarning: divide by zero encountered in true_divide
  if __name__ == '__main__':


array([[        inf,  1.28571429,  1.        ,  0.8       ,  2.33333333],
       [ 9.        ,  0.22222222,  1.66666667,  0.        ,  1.33333333],
       [ 1.        ,  0.75      ,  1.5       ,  0.        ,  0.        ],
       [ 4.        ,  1.5       ,  0.2       ,  0.55555556,  1.        ]])

### 矩阵的创建

In [15]:
np.mat([[1, 2, 3], [4, 5, 6]])

matrix([[1, 2, 3],
        [4, 5, 6]])

In [16]:
a

array([[8, 9, 2, 4, 7],
       [9, 2, 5, 0, 8],
       [5, 3, 3, 0, 0],
       [8, 3, 1, 5, 1]])

In [17]:
np.mat(a)

matrix([[8, 9, 2, 4, 7],
        [9, 2, 5, 0, 8],
        [5, 3, 3, 0, 0],
        [8, 3, 1, 5, 1]])

### 矩阵的运算

In [18]:
A = np.mat(a)
B = np.mat(b)

In [19]:
A + B

matrix([[ 8, 16,  4,  9, 10],
        [10, 11,  8,  9, 14],
        [10,  7,  5,  4,  9],
        [10,  5,  6, 14,  2]])

In [20]:
A - B

matrix([[ 8,  2,  0, -1,  4],
        [ 8, -7,  2, -9,  2],
        [ 0, -1,  1, -4, -9],
        [ 6,  1, -4, -4,  0]])

ValueError: shapes (4,5) and (4,5) not aligned: 5 (dim 1) != 4 (dim 0)

In [22]:
a = np.mat(np.random.randint(10, size=20).reshape(4, 5))
b = np.mat(np.random.randint(10, size=20).reshape(5, 4))

In [23]:
a * b

matrix([[156, 136,  83, 125],
        [131, 138,  68,  85],
        [172, 155, 129,  73],
        [ 53,  44,  15,  32]])

### Array常用函数

In [25]:
a = np.random.randint(10, size=20).reshape(4, 5)

In [26]:
np.unique(a)

array([0, 1, 2, 3, 4, 7, 9])

In [27]:
a

array([[2, 1, 4, 3, 7],
       [7, 0, 2, 3, 0],
       [4, 9, 7, 9, 0],
       [1, 9, 4, 2, 4]])