### 使用pickle序列化numpy array


In [2]:
import numpy as np
import pickle

In [3]:
x = np.arange(10)

In [4]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
f = open('x.pkl', 'wb')
pickle.dump(x, f)

In [13]:
ls

 驱动器 E 中的卷是 资料
 卷的序列号是 9680-46FC

 E:\DeepLearning\jupyter_code\jupyter notebook\python数据分析实战 的目录

2018/09/21  16:03    <DIR>          .
2018/09/21  16:03    <DIR>          ..
2018/09/21  16:01    <DIR>          .ipynb_checkpoints
2018/09/21  15:28             2,331 1.Anaconda与Jupyter notebook介绍.ipynb
2018/09/21  15:38             1,396 2.矩阵运算.ipynb
2018/09/21  15:48             8,408 3.Array的创建及访问.ipynb
2018/09/21  15:58            13,397 4.数组与矩阵运算.ipynb
2018/09/21  16:02             1,103 5.Array中的input和output.ipynb
2018/09/21  16:03                 0 x.pkl
               6 个文件         26,635 字节
               3 个目录 95,594,225,664 可用字节


In [14]:
f = open('x.pkl', 'rb')
pickle.load(f)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
np.save('one_array', x)

In [17]:
ls

 驱动器 E 中的卷是 资料
 卷的序列号是 9680-46FC

 E:\DeepLearning\jupyter_code\jupyter notebook\python数据分析实战 的目录

2018/09/21  16:06    <DIR>          .
2018/09/21  16:06    <DIR>          ..
2018/09/21  16:01    <DIR>          .ipynb_checkpoints
2018/09/21  15:28             2,331 1.Anaconda与Jupyter notebook介绍.ipynb
2018/09/21  15:38             1,396 2.矩阵运算.ipynb
2018/09/21  15:48             8,408 3.Array的创建及访问.ipynb
2018/09/21  15:58            13,397 4.数组与矩阵运算.ipynb
2018/09/21  16:04             2,966 5.Array中的input和output.ipynb
2018/09/21  16:06               120 one_array.npy
2018/09/21  16:05               195 x.pkl
               7 个文件         28,813 字节
               3 个目录 95,594,225,664 可用字节


In [19]:
np.load('one_array.npy')

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
y = np.arange(20)

In [21]:
y

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [26]:
np.savez('two_array.npz', a=x, b=y)

In [27]:
ls

 驱动器 E 中的卷是 资料
 卷的序列号是 9680-46FC

 E:\DeepLearning\jupyter_code\jupyter notebook\python数据分析实战 的目录

2018/09/21  16:08    <DIR>          .
2018/09/21  16:08    <DIR>          ..
2018/09/21  16:01    <DIR>          .ipynb_checkpoints
2018/09/21  15:28             2,331 1.Anaconda与Jupyter notebook介绍.ipynb
2018/09/21  15:38             1,396 2.矩阵运算.ipynb
2018/09/21  15:48             8,408 3.Array的创建及访问.ipynb
2018/09/21  15:58            13,397 4.数组与矩阵运算.ipynb
2018/09/21  16:06             5,608 5.Array中的input和output.ipynb
2018/09/21  16:06               120 one_array.npy
2018/09/21  16:08               474 tow_array.npz
2018/09/21  16:07               474 tw_array.npz
2018/09/21  16:08               474 two_array.npz
2018/09/21  16:05               195 x.pkl
              10 个文件         32,877 字节
               3 个目录 95,594,221,568 可用字节


In [29]:
c = np.load("two_array.npz")

In [ ]:
c