In [2]:
import pandas as pd
import numpy as np

In [3]:
s1 = pd.Series([1, 2, 3, 4])

In [4]:
s1

0    1
1    2
2    3
3    4
dtype: int64

In [6]:
s1.values

array([1, 2, 3, 4], dtype=int64)

In [7]:
s1.index

RangeIndex(start=0, stop=4, step=1)

In [8]:
s2 = pd.Series(np.arange(10))

In [9]:
s2

0    0
1    1
2    2
3    3
4    4
5    5
6    6
7    7
8    8
9    9
dtype: int32

In [10]:
s3 = pd.Series({'1': 1, '2': 2, '3': 3})

In [11]:
s3

1    1
2    2
3    3
dtype: int64

In [12]:
s3.values

array([1, 2, 3], dtype=int64)

In [13]:
s2.index

RangeIndex(start=0, stop=10, step=1)

In [14]:
s4 = pd.Series([1, 2, 3, 4], index=['a', 'b', 'c', 'd'])

In [15]:
s4

a    1
b    2
c    3
d    4
dtype: int64

In [16]:
s4.values

array([1, 2, 3, 4], dtype=int64)

In [17]:
s4.index

Index(['a', 'b', 'c', 'd'], dtype='object')

In [18]:
s4['a']

1

In [19]:
s4[s4>2]

c    3
d    4
dtype: int64

In [20]:
s4.to_dict()

{'a': 1, 'b': 2, 'c': 3, 'd': 4}

In [21]:
s5 = pd.Series(s4.to_dict())

In [22]:
s5

a    1
b    2
c    3
d    4
dtype: int64

In [25]:
index_1 = ['a', 'b', 'c', 'd', 'E']
s6 = pd.Series(s5, index=index_1)

In [26]:
s6

a    1.0
b    2.0
c    3.0
d    4.0
E    NaN
dtype: float64