In [1]:
import numpy as np
import pandas as pd
from pandas import Series, DataFrame

# Concatenate

In [2]:
arr1 = np.arange(9).reshape(3, 3)

In [3]:
arr1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [4]:
arr2 = np.arange(9).reshape(3, 3)

In [5]:
arr2

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [6]:
np.concatenate([arr1, arr2])

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8],
       [0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [7]:
np.concatenate([arr1, arr2], axis=1)

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5],
       [6, 7, 8, 6, 7, 8]])

In [8]:
s1 = Series([1, 2, 3], index=['X', 'Y', 'Z'])

In [9]:
s2 = Series([4, 5], index=['A', 'B'])

In [10]:
s1

X    1
Y    2
Z    3
dtype: int64

In [11]:
s2

A    4
B    5
dtype: int64

In [14]:
pd.concat([s1, s2])

X    1
Y    2
Z    3
A    4
B    5
dtype: int64

In [15]:
pd.concat([s1, s2], axis=1)

0    1
A  NaN  4.0
B  NaN  5.0
X  1.0  NaN
Y  2.0  NaN
Z  3.0  NaN

In [16]:
df1 = DataFrame(np.random.randn(4, 3), columns=['X', 'Y', 'Z'])

In [17]:
df1

X         Y         Z
0  1.146768 -1.007186 -1.869316
1 -1.773344 -0.120012 -0.338270
2 -1.882007 -0.839714  0.576451
3  1.117750 -0.309945  0.669008

In [18]:
df2 = DataFrame(np.random.randn(3, 3), columns=['X', 'Y', 'A'])

In [19]:
df2

X         Y         A
0 -0.155795  1.324868 -0.530668
1  0.397211  0.602421 -0.270971
2 -0.843017  0.415710 -1.542741

In [20]:
pd.concat([df1, df2])

A         X         Y         Z
0       NaN  1.146768 -1.007186 -1.869316
1       NaN -1.773344 -0.120012 -0.338270
2       NaN -1.882007 -0.839714  0.576451
3       NaN  1.117750 -0.309945  0.669008
0 -0.530668 -0.155795  1.324868       NaN
1 -0.270971  0.397211  0.602421       NaN
2 -1.542741 -0.843017  0.415710       NaN

# Combine

In [22]:
s1 = Series([2, np.nan, 4, np.nan], index=['A', 'B', 'C', 'D'])

In [23]:
s1

A    2.0
B    NaN
C    4.0
D    NaN
dtype: float64

In [24]:
s2 = Series([1, 2, 3, 4], index=['A', 'B', 'C', 'D'])

In [25]:
s2

A    1
B    2
C    3
D    4
dtype: int64

In [27]:
s1.combine_first(s2)  # 用s2填充s1

A    2.0
B    2.0
C    4.0
D    4.0
dtype: float64

In [28]:
df1 = DataFrame({'X':[1, np.nan, 3, np.nan], 'Y': [5, np.nan, 7, np.nan], 'Z': [9, np.nan, 11, np.nan]})

In [29]:
df1

X    Y     Z
0  1.0  5.0   9.0
1  NaN  NaN   NaN
2  3.0  7.0  11.0
3  NaN  NaN   NaN

In [30]:
df2 = DataFrame({'Z': [np.nan, 10, np.nan, 12], 'A': [1, 2, 3, 4]})

In [31]:
df2

A     Z
0  1   NaN
1  2  10.0
2  3   NaN
3  4  12.0

In [32]:
df1.combine_first(df2)

A    X    Y     Z
0  1.0  1.0  5.0   9.0
1  2.0  NaN  NaN  10.0
2  3.0  3.0  7.0  11.0
3  4.0  NaN  NaN  12.0